### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(BASSC_UI)
add_subdirectory(BASSC_UIContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    BASSC_UIplugin
    BASSC_UIContentplugin
    QtQuickDesignerComponents)